export const products = [
  {
    id: 'p1',
    name: 'جلابية الريم جملي مطفي قصة مثلث',
    slug: 'alreem-camel-triangle',
    category: 'الريم',
    categorySlug: 'alreem',
    description: 'تصميم أنيق بلمسة عصرية وقصة مثلث فاخرة.',
    price: 260,
    compareAtPrice: 320,
    stock: 10,
    rating: 4.8,
    reviewCount: 16,
    featured: true,
    image: '/images/products/alreem-camel.jpg',
  },
  {
    id: 'p2',
    name: 'جلابية النور برتقالي برو وايت',
    slug: 'alnoor-orange',
    category: 'النور',
    categorySlug: 'alnoor',
    description: 'إطلالة مشرقة بتفاصيل فاخرة تناسب جميع الأوقات.',
    price: 230,
    compareAtPrice: 290,
    stock: 8,
    rating: 4.7,
    reviewCount: 11,
    featured: true,
    image: '/images/products/alnoor-orange.jpg',
  },
  {
    id: 'p3',
    name: 'جلابية الأثير Silver Blush',
    slug: 'alatheer-silver-blush',
    category: 'الأثير',
    categorySlug: 'alatheer',
    description: 'نعومة راقية بلمسة أنثوية فاخرة.',
    price: 250,
    compareAtPrice: 300,
    stock: 12,
    rating: 4.9,
    reviewCount: 20,
    featured: false,
    image: '/images/products/alatheer-silver-blush.jpg',
  },
  {
    id: 'p4',
    name: 'جلابية المدى أزرق ملكي',
    slug: 'almada-blue',
    category: 'المدى',
    categorySlug: 'almada',
    description: 'تصميم ملكي يبرز الفخامة والبساطة.',
    price: 240,
    compareAtPrice: 300,
    stock: 7,
    rating: 4.6,
    reviewCount: 9,
    featured: false,
    image: '/images/products/almada-blue.jpg',
  },
  {
    id: 'p5',
    name: 'جلابية العروب خمري ذهبي',
    slug: 'alaroob-maroon-gold',
    category: 'العروب',
    categorySlug: 'alaroob',
    description: 'مزيج فاخر بين اللون الخمري والتفاصيل الذهبية.',
    price: 270,
    compareAtPrice: 330,
    stock: 5,
    rating: 4.9,
    reviewCount: 14,
    featured: true,
    image: '/images/products/alaroob-maroon-gold.jpg',
  },
  {
    id: 'p6',
    name: 'جلابية العروب أسود ياقوتي ذهبي',
    slug: 'alaroob-black-ruby',
    category: 'العروب',
    categorySlug: 'alaroob',
    description: 'فخامة اللون الأسود مع لمسة ياقوتية ذهبية.',
    price: 280,
    compareAtPrice: 340,
    stock: 6,
    rating: 5,
    reviewCount: 18,
    featured: true,
    image: '/images/products/alaroob-black-ruby.jpg',
  },
]
